config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'game#index'
  resources :game
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resource.rb
class Resource < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @games = Game.all 
  end

  def new 
    @game = Game.new
  end

  def create 
     Games.create(games_params)
     redirect_to_root_path 
  end

  private

  def games_params
    params.require(:game).permit(:name, :description)
  end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController

  def index
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/views/game/index.html.erb
<h1>Survey: What's your favorite game?</h1>

app/views/game/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter your Favorite Game</h1>
  <%= simple_form_for @game do |f| %>
    <%= f.input :name %>
    <%= f.input :comment %>
    <br />
    <%= f.submit 'Create', class: 'btn btn-primary' %>
  <% end %>
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miss R's Resources</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <h1>Miss Rachal's Student Resources</h1>
    <hr />
   <br /> 
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'home', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to new_game_path, class: 'nav-link' do %>
              <i class="fa fa-plus-circle"></i>
              Survey
            <% end %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
               <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <%= yield %>
  </body>

<footer>
  <div class="table">
    <td></td>

    <td>
        <p>
          <h3>If you have questions contact me by email, phone, or sign up for a 1-1 session:</h3>
        </p>
    <td>    
      <p><a href="https://srachal.youcanbook.me/" class="contact-link"><h4>1-1 Sign up</h4></a> &nbsp; &nbsp;<a href="mailto:srachal@insightaz.org" class="contact-link"><h4>srachal@insightaz.org</h4>
        </a>
      </p>
    </td>

    <td></td>
  </div>
    

</footer>
</html>